"""empty message

Revision ID: ecc983704af9
Revises: e3451be8ddd3
Create Date: 2020-07-09 21:49:43.019590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc983704af9'
down_revision = 'e3451be8ddd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('important', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET important = True WHERE important IS NULL;')
    op.alter_column('todos', 'important', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'important')
    # ### end Alembic commands ###
